//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTraining.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Applications()
        {
            this.Comments = new HashSet<Comments>();
        }
    
        public int ApplicationID { get; set; }
        public int UserID { get; set; }
        public int MasterID { get; set; }
        public int StatusID { get; set; }
        public int EquipmentID { get; set; }
        public string Defect { get; set; }
        public string DefectDescription { get; set; }
        public System.DateTime DatePosting { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Status Status { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
    }
}
